parameters:
    locale: en

framework:
    #esi:             ~
    translator:      { fallback: "%locale%" }
    secret:          "%env(APP_SECRET)%"
    router:
        strict_requirements: ~
#    form:            ~
#    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
#    session:
#        handler_id: ~
    fragments:       ~
    http_method_override: true
#    assets:
#        json_manifest_path: '%kernel.project_dir%/public/build/manifest.json'
    php_errors:
        log: true
